parameters:
  - name: environment
    type: string
    displayName: 'The deployment job environment'
  - name: serviceConnection
    type: string
    displayName: 'The service connection'
stages:
  - stage: Deploy
    displayName: 'Reset environment'
    jobs:
      - deployment: Deployment
        displayName: Deploy
        environment: '${{ parameters.environment }}'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  displayName: 'Download package artifact'
                  artifact: 'Development Hub'
                - task: PowerPlatformToolInstaller@0
                  displayName: 'Install Power Platform Build Tools'
                  inputs:
                    DefaultVersion: true
                - task: PowerPlatformDeployPackage@0
                  displayName: 'Deploy package'
                  inputs:
                    authenticationType: 'PowerPlatformEnvironment'
                    PowerPlatformEnvironment: '${{ parameters.serviceConnection }}'
                    PackageFile: '$(Pipeline.Workspace)/Development Hub/DevelopmentHub.Deployment.dll'