parameters:
  - name: environment
    type: string
    displayName: 'The deployment job environment'
  - name: resetServiceConnection
    type: string
    displayName: 'The reset service connection (needs to be an admin user)'
  - name: deployServiceConnection
    type: string
    displayName: 'The deployment service connection'
  - name: environmentVariableGroup
    displayName: 'The variable group containing the environment details'
    type: string
stages:
  - stage: Deploy
    displayName: 'Deploy package'
    jobs:
      - deployment: ResetEnvironment
        condition: and(succeeded(), eq(variables['resetEnvironment'], true))
        displayName: Reset environment
        environment: '${{ parameters.environment }}'
        variables:
          - group: '${{ parameters.environmentVariableGroup }}'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none
                - task: PowerPlatformToolInstaller@0
                  displayName: 'Install Power Platform Build Tools'
                  inputs:
                    DefaultVersion: true
                - task: PowerPlatformResetEnvironment@0
                  displayName: Reset environment
                  inputs:
                    authenticationType: 'PowerPlatformEnvironment'
                    PowerPlatformEnvironment: '${{ parameters.resetServiceConnection }}'
                    TargetRelease: 'Dynamics 365, version 9.0'
                    BaseLanguage: '1033'
                - task: PowerShell@2
                  displayName: 'Create admin application user for Azure DevOps'
                  inputs:
                    targetType: 'filePath'
                    filePath: 'scripts/Add-AdminApplicationUser.ps1'
                    failOnStderr: true
                    errorActionPreference: 'stop'
                    arguments: '-Username $(adminUserEmail) -Password (ConvertTo-SecureString -String "$(adminUserPassword)" -AsPlainText -Force) -ClientId $(serviceConnectionClientId) -FirstName Azure -LastName DevOps -Domain $(domain) -Url $(url) -OrganizationName $(organizationName)'
                - task: PowerShell@2
                  displayName: 'Create admin application user for Development Hub'
                  inputs:
                    targetType: 'filePath'
                    filePath: 'scripts/Add-AdminApplicationUser.ps1'
                    failOnStderr: true
                    errorActionPreference: 'stop'
                    arguments: '-Username $(adminUserEmail) -Password (ConvertTo-SecureString -String "$(adminUserPassword)" -AsPlainText -Force) -ClientId $(PACKAGEDEPLOYER_SETTINGS_SERVICEPRINCIPALCLIENTID) -FirstName Development -LastName Hub -Domain $(domain) -Url $(url) -OrganizationName $(organizationName)'
                - task: PowerShell@2
                  displayName: 'Create solution publisher'
                  inputs:
                    targetType: 'filePath'
                    filePath: 'scripts/New-SolutionPublisher.ps1'
                    failOnStderr: true
                    errorActionPreference: 'stop'
                    arguments: '-Username $(adminUserEmail) -Password (ConvertTo-SecureString -String "$(adminUserPassword)" -AsPlainText -Force) -DisplayName "Test Publisher" -UniqueName "testpublisher" -Prefix "test"'  
      - deployment: Deployment
        displayName: Deploy
        condition: not(failed('ResetEnvironment'))
        environment: '${{ parameters.environment }}'
        variables:
          - group: '${{ parameters.environmentVariableGroup }}'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  displayName: 'Download package artifact'
                  artifact: 'Development Hub'
                - task: PowerPlatformToolInstaller@0
                  displayName: 'Install Power Platform Build Tools'
                  inputs:
                    DefaultVersion: true
                - task: PowerPlatformDeployPackage@0
                  displayName: 'Deploy package'
                  inputs:
                    authenticationType: 'PowerPlatformSPN'
                    PowerPlatformSPN: '${{ parameters.deployServiceConnection }}'
                    PackageFile: '$(Pipeline.Workspace)/Development Hub/DevelopmentHub.Deployment.dll'
                  env:
                    PACKAGEDEPLOYER_SETTINGS_SERVICEPRINCIPALCLIENTSECRET: $(PACKAGEDEPLOYER_SETTINGS_SERVICEPRINCIPALCLIENTSECRET_SECRET)
                    PACKAGEDEPLOYER_SETTINGS_LICENSEDUSERPASSWORD: $(PACKAGEDEPLOYER_SETTINGS_LICENSEDUSERPASSWORD_SECRET)